### ISSUE TITLE
A complement, a couple bugs, and a suggestion

### ISSUE THREAD

**Issue by VaughnGH** [vgmoose/OpenBackupExtractor#2]
Hello,
Thanks for making such a useful utility! Your blog post on this project [0] really resonates with me--I can't believe there isn't a larger OSS following to liberating your phone's data.
Unfortunately I was unable to specifically select which types of files would be extracted (each checkbox, and the loading/progress bar, are grayed out and un-selectable). I am running MacOS 10.11.6, iOS 11.2.6.
Furthermore, the application unexpectedly quit amid a backup export, the error was:
```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9'
terminating with uncaught exception of type NSException
abort() called
```
Also, I would recommend potentially adding a preference for customizing the directory path for iTunes backups. This may be helpful if the backups are moved to another disk, or Apple decides to change the path down the line.

This tool is epic. Keep up the good work! (If I were a swift dev, I would certainly contribute ;p)

[0] https://vgmoose.com/blog/extracting-ios-voicemails-and-other-data-with-openbackuptool-2425971492/

**Comment by vgmoose** [comment]
Thank you for the positive feedback! I have made a new release [here](https://github.com/vgmoose/OpenBackupExtractor/releases/tag/1.1) that aims to address the bugs you brought up.

1. I believe that the error has to do with the way that I was checking file types (spawning a new `file` process for every file using NSTask). I've changed it to now use the same libmagic library that file uses, hopefully this should fix that error and also speed up the exporting time.

2. The old code to determine which files should be exported also is now cleaned up into [this mapping](https://github.com/vgmoose/OpenBackupExtractor/blob/master/Open%20Backup%20Extractor/SelectableTypesView.swift#L16-L28), where if the libmagic output matches something on the left, it exports it under the file extension on the right. This should allow the checkboxes to actually work with the selected filetypes.

3. Lastly, added an option under File -> Set iTunes Backup Directory to specify a different place where the backups are located. I'm not entirely satisfied with how that works right now, but it should work if the user needs to choose a different location.
